### ISSUE TITLE
Compatibility Issues with the String.prototype.at() Method

### ISSUE THREAD

**Issue by AllenYu0118** [unjs/destr#101]
### Environment

"node": ">=16",
"pnpm": ">=8.4.0"

### Reproduction

Please use a browser with a version below iOS 14.4 to access.
https://stackblitz.com/edit/typescript-hlusqb?file=index.ts

The results displayed by the Chrome browser on iOS 14.4.
<img src="https://github.com/unjs/destr/assets/7732447/ce3a5653-8d44-42d8-ab47-092fa89a866b" width="500" />

### Describe the bug

This is just a compatibility issue. When in iOS 14, an error occurs due to the incompatibility of the browser caused by the use of the "at" method. I'm not sure whether to fix it in this library, compile this library in my project, or provide a polyfill.

System Infomation
<img src="https://github.com/unjs/destr/assets/7732447/5df11b82-6b3d-4d3c-ab78-2aecee821d72" width="500" />

### Additional context

We use Nuxt (v3.8.2) to develop the application. It is possible that the use of `renderJsonPayloads: true` in the experimental features causes the data to be parsed with destr. In most cases, this is not a problem, but someone reported a white screen issue on iOS 14.

**Comment by RazorSiM** [comment]
I second this issue. I have **destr** as a dependency of **ofetch** and the update from `2.0.1` to `2.0.2` broke the app running on Electron 13, that uses Chromium 91.

With Chromium 93, the issue is not there anymore, but we cannot update Electron to v14.

This is where the problem is:
https://github.com/unjs/destr/blob/39f75a17266ed9e38357b9079b0bc58a202ab700/src/index.ts#L41
